### ISSUE TITLE
Cleaned version remove Nashorn ScriptEngine

### ISSUE THREAD

**Issue by edwmamedov** [frol/docker-alpine-oraclejdk8#27]
subj. we can't find javascript engine in cleaned build at runtime.

**Comment by frol** [comment]
Does `:full` tag work for you?

**Comment by edwmamedov** [comment]
I didn't try, we can not change jdk version to full.

**Comment by frol** [comment]
What is the exact reason which prevents you from using a tag which is different from `cleaned`?

I don't have numbers off the top of my head, but I guess that JS engine was quite heavy, so I cleaned it up since it doesn't seem to be quite commonly used, and there is always an option to go with `:full` if needed.

**Comment by frol** [comment]
By the way, I have inspected the Dockerfile and it seems that [`nashorn.jar` gets deleted only for the `:slim` tag](https://github.com/frol/docker-alpine-oraclejdk8/blob/8a5a84eaef3f6d8a70bf0a9edfd12889194c7acd/Dockerfile#L48), thus I would expect it working in the `:cleaned` version of the image.

**Comment by edwmamedov** [comment]
@frol we have lot of microservices that coming soon to production, we can't do such things only to support annotation that relies on javascript functionality (hibernate validator).  I don't think that it is good idea to remove jsr-223 support from java.

**Comment by frol** [comment]
I understand your desire to keep away from such a breaking change, but even if I "fix" it somehow (as I pointed out in my previous message, I don't expect Nashorn being deleted in the `:cleaned` tag, so it is unclear what else might be the cause), that would most probably become a breaking change for you anyway... I can only suggest you fork the image to be in control of what you need.

> I don't think that it is good idea to remove jsr-223 support from java.

I don't write Java code at all, but I have been using this image (in fact, I use `:slim` version of it) to build and package exising Java projects for over 3 years now (and Docker Hub stats show that this image has been pulled over 1M times, so I would expect reports if anything like this is a problem for anyone).

In any case, testing with `:full` tag may at least help us to make sure that the issue is caused by some module being missing instead of something else (e.g. hidden glibc issue)

**Comment by edwmamedov** [comment]
Sorry, we are extending your Dockerfile with slim version, that remove nashorn engine.
