### ISSUE TITLE
How to choose java u version

### ISSUE THREAD

**Issue by benjacarp** [frol/docker-alpine-oraclejdk8#34]
Is there a way to set the java u version like 8u171 in the dockerFile or somewhere else just to avoid downloading the latest each time?

**Comment by frol** [comment]
There are quite a few tags on Docker Hub: https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/tags/

Thus, you can use `frovlad/alpine-oraclejdk8:8.192.12-slim`, for example.

Just keep in mind, that they don't receive any updates (mostly due to the fact that Oracle (re)moves the old releases), i.e. the base image will get outdated.
