### ISSUE TITLE
Oracle BCL license agreement

### ISSUE THREAD

**Issue by borlafu** [frol/docker-alpine-oraclejdk8#6]
This code is distributed under MIT license, but building the image virtually accepts Oracle's BCL license: http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Actually, by running the built image the user is using the software (Oracle's JRE/JDK) without explicitly accepting (and not even knowing about) the BCL license.

I believe this is the reason why the official Java docker images are openJDK and not Oracle JDK, and this code may be infringing the license agreement with Oracle.

**Comment by frol** [comment]
@borlafu I have read the information about the licensing, and the best I can do is to remove the image from Docker Hub. Is this what you want?

BTW, MIT licensing only affects the text of the Dockerfile, this repository doesn't use Oracle Java. Anybody can grab the Dockerfile and build their images, thus, accepting the BCL license on their behalf.

**Comment by borlafu** [comment]
Well, I don't want anything I'm just rising the concern, in case you were not aware :).
I believe that if this didn't existed before it's because Oracle's license does not allow it, or there's a legal risk around it.

**Comment by cstroe** [comment]
@frol Running the OracleJDK without accepting the binary code license is not allowed.  Anyone downloading and using your image in a production environment is putting themselves at legal risk.

This can be fixed by adding a disclaimer that users of your docker image must accept the [Oracle Binary Code License Agreement](http://www.oracle.com/technetwork/java/javase/terms/license/index.html).  For example, this image does just that: https://hub.docker.com/r/streamsets/datacollector/ because they include OracleJDK in their image.

**Comment by borlafu** [comment]
Simple an easy way to solve the license issue :)
